os: linux
dist: focal
language: shell

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - python-gflags

jobs:
  include:
    - dist: trusty
    - dist: xenial
    - dist: bionic
    - dist: eoan
    - dist: focal

# language: cpp  # not bash

# install: true  # python -c 'import sys ; print("Python {}".format(sys.version))'

# before_script:
#  - python --version
#  - pip --version
#  - python3 --version || true
#  - python3 -m pip --version || true

# script: pyenv install --list
