os: linux
dist: focal
language: shell

jobs:
  include:
    - dist: precise
    - dist: trusty
    - dist: xenial
    - dist: bionic
    - dist: focal
  allow_failures:
    - dist: precise

# install: true  # python -c 'import sys ; print("Python {}".format(sys.version))'

before_script:
  - python --version
  - pip --version
  - python3 --version || true
  - python3 -m pip --version || true

script:
  - pyenv version
  - pyenv versions
  - pyenv install --list
