os: linux
dist: focal
language: shell

dist:
  - trusty
  - xenial
  - bionic
  - eoan
  - focal

# language: cpp  # not bash

install: true  # python -c 'import sys ; print("Python {}".format(sys.version))'

# before_script:
#  - python --version
#  - pip --version
#  - python3 --version || true
#  - python3 -m pip --version || true

script: pyenv install --list
